name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows us to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # allocates a particular runner to run our workflow
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out our repository to actions file under $GITHUB_WORKSPACE, so our job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      #As it is a python project so we are setting python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
           python-version: '3.x'
           
      - name: Install dependencies
        run: |
           python -m pip install --upgrade pip
           pip install build
      - name: Build and push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: bhagbat/sample
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
